### ISSUE TITLE
Does windows support the libs

### ISSUE THREAD

**Issue by juine** [lyst/rpforest#15]
In win7 environment, when i install rpforest ,i met the problem. i use vs2015. 
the complie error informatios:
C:\Users\juine\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python
\9.0\VC\Bin\cl.exe /c logo /Ox /MD /W3 /GS- /DNDEBUG -ID:\Python27\lib\site-p
ackages\numpy\core\include -ID:\Python27\include -ID:\Python27\PC /Tprpforest/rp
forest_fast.cpp /Fobuild\temp.win32-2.7\Release\rpforest/rpforest_fast.obj -ffas
t-math
    cl : Command line warning D9002 : ignoring unknown option '-ffast-math'
    rpforest_fast.cpp
    d:\python27\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_ap
i.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_N
O_DEPRECATED_API NPY_1_7_API_VERSION
    rpforest/rpforest_fast.cpp(271) : fatal error C1083: Cannot open include fil
e: 'stdint.h': No such file or directory
    error: command 'C:\\Users\\juine\\AppData\\Local\\Programs\\Common\\Microsof
t\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

**Comment by maciejkula** [comment]
Can you pull and try https://github.com/lyst/rpforest/pull/16 please?

**Comment by juine** [comment]
I have tried.It also has this problem.

**Comment by juine** [comment]
Thanks,it installs success. But When i do python setup.py test,it also met errors.
the errors are:
Writing c:\users\juine\appdata\local\temp\easy_install-hcwxcu\scipy-0.17.0\setup
.cfg
Running scipy-0.17.0\setup.py -q bdist_egg --dist-dir c:\users\juine\appdata\loc
al\temp\easy_install-hcwxcu\scipy-0.17.0\egg-dist-tmp-_ut4xq
D:\Python27\lib\site-packages\numpy\distutils\system_info.py:1427: UserWarning:

    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
D:\Python27\lib\site-packages\numpy\distutils\system_info.py:1438: UserWarning:

    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  warnings.warn(LapackNotFoundError.__doc__)
D:\Python27\lib\site-packages\numpy\distutils\system_info.py:1441: UserWarning:

    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  warnings.warn(LapackSrcNotFoundError.__doc__)
Running from scipy source directory.
error: no lapack/blas resources found

**Comment by juine** [comment]
I forget install scipy. Now it can work.Thanks

**Comment by maciejkula** [comment]
Fantastic. I'll merge #16 and bundle it into the next release.
