### ISSUE TITLE
Is rpforest supports custom similarity/distance function

### ISSUE THREAD

**Issue by hiyijian** [lyst/rpforest#17]
hi, @maciejkula ,
According to your paper titled "Metadata Embeddings for User and Item Cold-start Recommendations", lyst generate recommendation using lightfm and some kind of ANN algorithm. So I came to rpforest in lyst's repository and I think maybe that's exactly the ANN.
Now Suppose that we have trained a lightfm model, include embeddings and bias. It seems that it is still hard to rapidly generate top-k recommendation using rpforest, Since as Readme said, rpforest is based on cosine similarity, however,  the score for a user-item pair in lightfm is the sum of a dot product of two embeddings and two bias. 
So my question is:

> Is rpforest supports custom similarity/distance function, or some other way can achieve top-k recommendation?

thanks
jianyi

**Comment by maciejkula** [comment]
You are right, rpforest is not built for user-item recommendations. It's more suitable for item-item recommendations (where the item vectors themselves can be extracted from the metadata embedding model).

**Comment by hiyijian** [comment]
so is there a way to rapidly recommend items for user? maybe  it is nothing about rpforest, but can you give me some hints?

**Comment by maciejkula** [comment]
One possibility, if you don't mind discarding item biases, is to normalise the item and user vectors to unit length and use those via rpforest. There are many methods which do this during training, something similar might be possible for LightFM.

Separately, there are papers describing ANN structures for dot products (ALSH comes to mind http://papers.nips.cc/paper/5329-asymmetric-lsh-alsh-for-sublinear-time-maximum-inner-product-search-mips.pdf). Implementing these in rpforst could be interesting.

Is you problem very large?

**Comment by hiyijian** [comment]
I am not quite sure what you mean by large. Dataset? yes. I have 6,000,000+ items and 1,000,000+ users. it's quite hard to do recommend using brute-force search.
Thanks. Got it~~. I used to think about discarding biases. That should be a reasonable solution. And I also found an algorithm called [kgraph](http://www.kgraph.org/) supports user-defined similarity. I will try both.
Thanks a lot

**Comment by maciejkula** [comment]
Yep, sounds like you need something better than brute search.

Let me know how kgraph works for you. It looks good and I'd really like a good explanation of how it works.

**Comment by maciejkula** [comment]
By the way, Etsy have something for approximate inner product search: https://github.com/etsy/Conjecture/blob/master/src/main/scala/com/etsy/conjecture/scalding/FastKNN.scala

**Comment by musicformellons** [comment]
This might be of interest as well:
https://github.com/erikbern/ann-benchmarks

**Comment by musicformellons** [comment]
And this:
https://github.com/falconn-lib/falconn

**Comment by iserko** [comment]
Closed due to inactivity

**Comment by trepca** [comment]
🥺
